name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  release-script:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: release-script
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Copy config files
        run: cp config.template.js config.js
      - name: Install dependencies
        run: npm ci
      - name: Run Lint Checks
        run: npm run lint
